### ISSUE TITLE
The PNG file generated by v7 is blur than by v6

### ISSUE THREAD

**Issue by daoqiclub** [parsimonhi/maxiGos#1]
The png format picture generated by version 6.xx is very sharp, all lines are very clear. Somehow version 7 gives a bigger picture, but lines are not clear.

![V6_V7](https://user-images.githubusercontent.com/98371642/152666119-5c927502-bbe9-4892-b8df-967f72fc34c1.png)

**Comment by ohiliazov** [comment]
+1 on this. It would be great to have PNG with better resolution than now.
Thank you for creating such a good online editor!

**Comment by parsimonhi** [comment]
This is not really a problem a PNG resolution (a PNG image is just a compressed set of pixels), but a problem of displaying lines that have not integer coordinates and integer width.

The major difference between maxiGos V6 and V7 is that the goban was drawn using a CANVAS in V6 and is drawn in V7 using a SVG. When displaying the SVG on a device (or when transforming a SVG in a pixel image such as PNG), the resulting coordinates and width of the goban lines are not necessary integers even if they are integer in the SVG. So it leads to some differences when displaying the goban.

The new approach (using a SVG) is more flexible because the resolution is "infinite" and one does not have to take care of the size of the container where one displays the image. But depending on some conditions (type of the device, type of the browser, screen resolution, css you are using, size of the goban, etc.), the display of the goban lines could be better ... or worse.

There are so many different possible conditions and constraints that can change the result that it is difficult to guarantee anything.

Anyways, when editing a diagram using for instance maxigos-minimalist-edit.js without any modification, you can try to increase the size of the goban using the menu "View" => "Zoom+" or "Zoom-" of maxiGos. May be it can solve your problem (this is the simplest way to increase/decrease the size of the generated PNG).

You can also try to use the SVG button instead of the PNG button when generating an image from maxigos-minimalist-edit.js. The resolution is in this case "infinite" (SVG images are not pixel images but vectoriel images). But it doesn't mean you will avoid a blurred effect because it depends of your screen definition and the way your device is "rounding" the pixels when displaying a line.

You can also try to change maxigos-minimalist-edit.js code. For instance, just replace r=2 by r=10 (it appears twice in maxigos-minimalist-edit.js code). This will increase the size of the PNG image and therefore you will be able to make a smaller PNG with an apparent better "resolution" if you want to do it. But as above, the result depends of your screen definition and the way your device is "rounding" the pixels when displaying a line.

Another way could be to generate a PNG where the elements of the goban have exactly the same coordinates as in the SVG, and where the coordinates and width of the lines are integer (in the PNG). The drawback is that the PNG will not have the same size in pixels as the goban drawn on your page (most of the time, the goban is shrink or stretch by the css and its final size depends of the screen resolution).

To do so, modify maxigos-minimalist-edit.js code as below:

1) replace
>
		r=2
by
>
		r=1

2) replace
>
		mxG.D[mxG.K].a.gridPadding=2;
by
>
		mxG.D[mxG.K].a.gridPadding=2.5;

3) replace
> 
		e2.setAttribute("width",b.width*r+"");
		e2.setAttribute("height",b.height*r+"");
by
> 
		let vb=e1.getAttribute("viewBox").split(" ");
		e2.setAttribute("width",vb[2]*r+"");
		e2.setAttribute("height",vb[3]*r+"");

4) replace
>
		this.sw4grid="1.125";
by
>
		this.sw4grid="1";

**Comment by daoqiclub** [comment]
> This is not really a problem a PNG resolution (a PNG image is just a compressed set of pixels), but a problem of displaying lines that have not integer coordinates and integer width.
> 
> The major difference between maxiGos V6 and V7 is that the goban was drawn using a in V6 and is drawn in V7 using a . When displaying the SVG on a device (or when transforming a SVG in a pixel image such as PNG), the resulting coordinates and width of the goban lines are not necessary integers even if they are integer in the SVG. So it leads to some differences when displaying the goban.
> 
> The new approach (using a SVG) is more flexible because the resolution is "infinite" and one does not have to take care of the size of the container where one displays the image. But depending on some conditions (type of the device, type of the browser, screen resolution, css you are using, size of the goban, etc.), the display of the goban lines could be better ... or worse.
> 
> There are so many different possible conditions and constraints that can change the result that it is difficult to guarantee anything.
> 
> Anyways, when editing a diagram using for instance maxigos-minimalist-edit.js without any modification, you can try to increase the size of the goban using the menu "View" => "Zoom+" or "Zoom-" of maxiGos. May be it can solve your problem (this is the simplest way to increase/decrease the size of the generated PNG).
> 
> You can also try to use the SVG button instead of the PNG button when generating an image from maxigos-minimalist-edit.js. The resolution is in this case "infinite" (SVG images are not pixel images but vectoriel images). But it doesn't mean you will avoid a blurred effect because it depends of your screen definition and the way your device is "rounding" the pixels when displaying a line.
> 
> You can also try to change maxigos-minimalist-edit.js code. For instance, just replace r=2 by r=10 (it appears twice in maxigos-minimalist-edit.js code). This will increase the size of the PNG image and therefore you will be able to make a smaller PNG with an apparent better "resolution" if you want to do it. But as above, the result depends of your screen definition and the way your device is "rounding" the pixels when displaying a line.
> 
> Another way could be to generate a PNG where the elements of the goban have exactly the same coordinates as in the SVG, and where the coordinates and width of the lines are integer (in the PNG). The drawback is that the PNG will not have the same size in pixels as the goban drawn on your page (most of the time, the goban is shrink or stretch by the css and its final size depends of the screen resolution).
> 
> To do so, modify maxigos-minimalist-edit.js code as below:
> 
> 1. replace
> 
> > 
> 
> ```
> 	r=2
> ```
> 
> by
> 
> > 
> 
> ```
> 	r=1
> ```
> 
> 2. replace
> 
> > 
> 
> ```
> 	mxG.D[mxG.K].a.gridPadding=2;
> ```
> 
> by
> 
> > 
> 
> ```
> 	mxG.D[mxG.K].a.gridPadding=2.5;
> ```
> 
> 3. replace
> 
> > 
> 
> ```
> 	e2.setAttribute("width",b.width*r+"");
> 	e2.setAttribute("height",b.height*r+"");
> ```
> 
> by
> 
> > 
> 
> ```
> 	let vb=e1.getAttribute("viewBox").split(" ");
> 	e2.setAttribute("width",vb[2]*r+"");
> 	e2.setAttribute("height",vb[3]*r+"");
> ```
> 
> 4. replace
> 
> > 
> 
> ```
> 	this.sw4grid="1.125";
> ```
> 
> by
> 
> > 
> 
> ```
> 	this.sw4grid="1";
> ```

Great job! This is what I am waiting for.
Thank you very much!

**Comment by ohiliazov** [comment]
Thank you for the fix idea @parsimonhi !
I implemented this and deployed to https://maxigos-minimalist-edit.vercel.app/.

**Comment by parsimonhi** [comment]
> Great job! This is what I am waiting for.

Thank you for your feedback.

> Thank you for the fix idea @parsimonhi ! I implemented this and deployed to https://maxigos-minimalist-edit.vercel.app/.

Nice result !
